name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          cargo install --version=0.2.0 sqlx-cli --no-default-features --features postgres
          SKIP_DOCKER=true ./scripts/init_db.sh
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
